#include <noggit/errorHandling.h>
#include <noggit/Log.h>

#include <csignal>
#include <cstdio>
#include <exception>
#include <string>
#include <vector>

#ifndef WIN32
  #include <execinfo.h>
#else
  #include <win/StackWalker.h>
  #include <errhandlingapi.h>
  #include <windows.h>
  #include <DbgHelp.h>
  #pragma comment(lib, "dbghelp.lib")
#endif

namespace Noggit
{
  void printStacktrace()
  {
#ifndef WIN32
    std::vector<void*> frames  (32);

    std::size_t actual  (0);
    while ((actual = backtrace (frames.data(), frames.size())) == frames.size())
    {
      frames.resize (frames.size() * 2);
    }
    frames.resize (actual);
    char** strings (backtrace_symbols (frames.data(), frames.size()));

    LogError << "Obtained " << frames.size() << " stack frames." << std::endl;

    for (size_t i (0); i < frames.size(); ++i)
      LogError << "- " << strings[i] << std::endl;

    free (strings);
#else
    StackWalker sw;
    sw.ShowCallstack();
#endif
  }

  namespace
  {
#ifdef _WIN32
    void write_minidump(EXCEPTION_POINTERS* ep);   // defined below
#endif

    void leave (int sig)
    {
      // Reset to defaults.
      signal (SIGABRT, SIG_DFL);
      signal (SIGFPE, SIG_DFL);
      signal (SIGILL, SIG_DFL);
      signal (SIGSEGV, SIG_DFL);
      signal (SIGTERM, SIG_DFL);

      std::string description;
      std::string sign;

      switch (sig)
      {
      case SIGABRT:
        sign = "SIGABRT";
        description = "Abnormal termination, such as instigated by the abort function. (Abort.)";
        break;
      case SIGFPE:
        sign = "SIGFPE";
        description = "Erroneous arithmetic operation, such as divide by 0 or overflow. (Floating point exception.)";
      break;
      case SIGILL:
        sign = "SIGILL";
        description = "An ‘invalid object program’ has been detected. This usually means that there is an illegal instruction in the program. (Illegal instruction.)";
        break;
      case SIGINT:
        sign = "SIGINT";
        description = "Interactive attention signal; on interactive systems this is usually generated by typing some ‘break-in’ key at the terminal. (Interrupt.)";
        break;
      case SIGSEGV:
        sign = "SIGSEGV";
        description = "Invalid storage access; most frequently caused by attempting to store some value in an object pointed to by a bad pointer. (Segment violation.)";
        break;
      case SIGTERM:
        sign = "SIGTERM";
        description = "Termination request made to the program. (Terminate.)";
        break;
      default:
        sign = "SIGUNK";
        description = "Unknown Exception!";
        break;
      }

      LogError << "There was an exception of type \""
        << sign
        << "\"\n\""
        << description
        << "\".\nPlease excuse the inconvenience. You may want to report this error including the log to the developers.\n"
        << std::endl;

      printStacktrace();

      // NEVER exit() from a crash/signal context: it runs the static destructors on a broken
      // process with live worker threads. That teardown (ModelManager -> ~Model -> texture
      // release -> TextureManager erase) crashed AGAIN every time, eating the report and the
      // log flush -- the "traceless Stormwind crash". Die hard instead, after a best-effort dump.
#ifdef _WIN32
      write_minidump(nullptr);
      TerminateProcess(GetCurrentProcess(), 128 + sig);
#else
      _Exit (sig);
#endif
    }

#ifdef _WIN32
    // ---- crash forensics -------------------------------------------------------------------
    // Some crash classes never reach SetUnhandledExceptionFilter (fail-fast /GS stack-buffer
    // overruns, some heap-corruption reports, std::terminate paths) -- those died TRACELESS.
    // Three additions close the gap:
    //   1. write_minidump(): a .dmp next to noggit.exe, loadable in VS/WinDbg with our .pdb.
    //   2. a vectored first-chance logger: writes code+address+module to noggit_fatal.txt
    //      via plain stdio (the LogError stream may be locked by the crashing thread).
    //   3. std::set_terminate: names the uncaught C++ exception before dying.

    void write_minidump(EXCEPTION_POINTERS* ep)
    {
      static LONG once = 0;
      if (InterlockedExchange(&once, 1))
        return;

      char path[MAX_PATH];
      std::snprintf(path, sizeof(path), "noggit_crash_%lu.dmp", GetCurrentProcessId());
      HANDLE file = CreateFileA(path, GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
      if (file == INVALID_HANDLE_VALUE)
        return;

      MINIDUMP_EXCEPTION_INFORMATION mei;
      mei.ThreadId = GetCurrentThreadId();
      mei.ExceptionPointers = ep;
      mei.ClientPointers = FALSE;

      MiniDumpWriteDump(GetCurrentProcess(), GetCurrentProcessId(), file,
                        static_cast<MINIDUMP_TYPE>(MiniDumpWithIndirectlyReferencedMemory | MiniDumpScanMemory),
                        ep ? &mei : nullptr, nullptr, nullptr);
      CloseHandle(file);
    }

    void log_fatal_sidechannel(EXCEPTION_POINTERS* ep)
    {
      FILE* f = std::fopen("noggit_fatal.txt", "a");
      if (!f)
        return;
      auto const* rec = ep->ExceptionRecord;
      std::fprintf(f, "FATAL exception 0x%08lX at %p (thread %lu)\n",
                   static_cast<unsigned long>(rec->ExceptionCode), rec->ExceptionAddress, GetCurrentThreadId());
      if (rec->ExceptionCode == EXCEPTION_ACCESS_VIOLATION && rec->NumberParameters >= 2)
      {
        std::fprintf(f, "  %s address %p\n", rec->ExceptionInformation[0] ? "write to" : "read from",
                     reinterpret_cast<void*>(rec->ExceptionInformation[1]));
      }
      HMODULE mod = nullptr;
      if (GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                             reinterpret_cast<LPCSTR>(rec->ExceptionAddress), &mod) && mod)
      {
        char name[MAX_PATH] = {};
        GetModuleFileNameA(mod, name, MAX_PATH);
        std::fprintf(f, "  in module %s (base %p, offset +0x%llx)\n", name, static_cast<void*>(mod),
                     static_cast<unsigned long long>(reinterpret_cast<char const*>(rec->ExceptionAddress)
                                                     - reinterpret_cast<char const*>(mod)));
      }
      std::fflush(f);
      std::fclose(f);
    }

    LONG WINAPI first_chance_fatal_logger(EXCEPTION_POINTERS* ep)
    {
      auto const code = ep->ExceptionRecord->ExceptionCode;
      // Codes that can kill the process without reaching the unhandled filter.
      // (C++ exceptions 0xE06D7363 and guarded probes pass through untouched.)
      if (code == EXCEPTION_STACK_OVERFLOW
       || code == 0xC0000374 /* STATUS_HEAP_CORRUPTION */
       || code == 0xC0000409 /* STATUS_STACK_BUFFER_OVERRUN (fail-fast) */)
      {
        static LONG logged = 0;
        if (InterlockedIncrement(&logged) <= 3)
        {
          log_fatal_sidechannel(ep);
          write_minidump(ep);
        }
      }
      else if (code == EXCEPTION_ACCESS_VIOLATION)
      {
        static LONG av_logged = 0;
        if (InterlockedIncrement(&av_logged) <= 5)
        {
          log_fatal_sidechannel(ep);
          // This project compiles with /EHa, so catch(...) SWALLOWS access violations (the
          // async loader "handles" them as failed loads and the process limps on) -- the
          // unhandled filter never runs and the true first fault was never captured. Write the
          // dump at FIRST chance instead: the once-guard in write_minidump keeps it to one.
          write_minidump(ep);
        }
      }
      return EXCEPTION_CONTINUE_SEARCH;
    }
    // ----------------------------------------------------------------------------------------

    LONG WINAPI windows_exception_handler(EXCEPTION_POINTERS * ExceptionInfo)
    {
      auto code = ExceptionInfo->ExceptionRecord->ExceptionCode;

      switch (code)
      {
      case EXCEPTION_ACCESS_VIOLATION: LogError << "EXCEPTION_ACCESS_VIOLATION" << std::endl; break;
      case EXCEPTION_DATATYPE_MISALIGNMENT: LogError << "EXCEPTION_DATATYPE_MISALIGNMENT" << std::endl; break;
      case EXCEPTION_BREAKPOINT: LogError << "EXCEPTION_BREAKPOINT" << std::endl; break;
      case EXCEPTION_SINGLE_STEP: LogError << "EXCEPTION_SINGLE_STEP" << std::endl; break;
      case EXCEPTION_ARRAY_BOUNDS_EXCEEDED: LogError << "EXCEPTION_ARRAY_BOUNDS_EXCEEDED" << std::endl; break;
      case EXCEPTION_FLT_DENORMAL_OPERAND: LogError << "EXCEPTION_FLT_DENORMAL_OPERAND" << std::endl; break;
      case EXCEPTION_FLT_DIVIDE_BY_ZERO: LogError << "EXCEPTION_FLT_DIVIDE_BY_ZERO" << std::endl; break;
      case EXCEPTION_FLT_INEXACT_RESULT: LogError << "EXCEPTION_FLT_INEXACT_RESULT" << std::endl; break;
      case EXCEPTION_FLT_INVALID_OPERATION: LogError << "EXCEPTION_FLT_INVALID_OPERATION" << std::endl; break;
      case EXCEPTION_FLT_OVERFLOW: LogError << "EXCEPTION_FLT_OVERFLOW" << std::endl; break;
      case EXCEPTION_FLT_STACK_CHECK: LogError << "EXCEPTION_FLT_STACK_CHECK" << std::endl; break;
      case EXCEPTION_FLT_UNDERFLOW: LogError << "EXCEPTION_FLT_UNDERFLOW" << std::endl; break;
      case EXCEPTION_INT_DIVIDE_BY_ZERO: LogError << "EXCEPTION_INT_DIVIDE_BY_ZERO" << std::endl; break;
      case EXCEPTION_INT_OVERFLOW: LogError << "EXCEPTION_INT_OVERFLOW" << std::endl; break;
      case EXCEPTION_PRIV_INSTRUCTION: LogError << "EXCEPTION_PRIV_INSTRUCTION" << std::endl; break;
      case EXCEPTION_IN_PAGE_ERROR: LogError << "EXCEPTION_IN_PAGE_ERROR" << std::endl; break;
      case EXCEPTION_ILLEGAL_INSTRUCTION: LogError << "EXCEPTION_ILLEGAL_INSTRUCTION" << std::endl; break;
      case EXCEPTION_NONCONTINUABLE_EXCEPTION: LogError << "EXCEPTION_NONCONTINUABLE_EXCEPTION" << std::endl; break;
      case EXCEPTION_STACK_OVERFLOW: LogError << "EXCEPTION_STACK_OVERFLOW" << std::endl; break;
      case EXCEPTION_INVALID_DISPOSITION: LogError << "EXCEPTION_INVALID_DISPOSITION" << std::endl; break;
      case EXCEPTION_GUARD_PAGE: LogError << "EXCEPTION_GUARD_PAGE" << std::endl; break;
      case EXCEPTION_INVALID_HANDLE: LogError << "EXCEPTION_INVALID_HANDLE" << std::endl; break;
#ifdef STATUS_POSSIBLE_DEADLOCK
      case EXCEPTION_POSSIBLE_DEADLOCK: LogError << "EXCEPTION_POSSIBLE_DEADLOCK" << std::endl; break;
#endif
      default:
        LogError << "Exception code=" << code << std::endl;
      }

      log_fatal_sidechannel(ExceptionInfo);   // survives even if the Log stream is wedged
      printStacktrace();
      write_minidump(ExceptionInfo);
      LogError << "Minidump written next to noggit.exe (noggit_crash_<pid>.dmp); "
                  "details also in noggit_fatal.txt" << std::endl;

      return EXCEPTION_CONTINUE_SEARCH;
    }
#endif

  }

  void RegisterErrorHandlers()
  {
#ifdef _WIN32
    SetUnhandledExceptionFilter(windows_exception_handler);
    AddVectoredExceptionHandler(1 /* call first */, first_chance_fatal_logger);

    // uncaught C++ exception (e.g. thrown off a thread without a catch) -> name it before dying;
    // the default terminate just aborts, which was one of the traceless-crash paths.
    std::set_terminate([]
    {
      if (FILE* f = std::fopen("noggit_fatal.txt", "a"))
      {
        std::fprintf(f, "std::terminate called (thread %lu)", GetCurrentThreadId());
        if (auto e = std::current_exception())
        {
          try { std::rethrow_exception(e); }
          catch (std::exception const& ex) { std::fprintf(f, " -- uncaught std::exception: %s", ex.what()); }
          catch (...)                      { std::fprintf(f, " -- uncaught non-std exception"); }
        }
        std::fprintf(f, "\n");
        std::fclose(f);
      }
      write_minidump(nullptr);
      std::abort();
    });

    // Do NOT register signal(SIGSEGV/SIGFPE/SIGILL) on Windows: the CRT implements those via the
    // __except filter wrapped around main (exe_common.inl), which CLAIMS hardware exceptions
    // before the unhandled-exception filter can ever run. Crashes then died through
    // leave() -> exit() with no minidump and an unflushed log. With them unregistered, real
    // faults reach windows_exception_handler with full EXCEPTION_POINTERS (side-channel log,
    // stack trace, minidump). SIGABRT/SIGTERM are CRT-raised, not hardware, and stay useful.
    signal (SIGABRT, leave);
    signal (SIGTERM, leave);
#else

    signal (SIGABRT, leave);
    signal (SIGFPE, leave);
    signal (SIGILL, leave);
    signal (SIGSEGV, leave);
    signal (SIGTERM, leave);
#endif
  }
}
